require("core.impatient")

require("plugins")

require("config.tokyonight")
require("config.dashboard")
require("config.toggleterm")
require("config.gitsigns")
require("config.lir")
require("config.harpoon")
require("config.scrollbar")
require("config.windows")
require("config.indent")
require("config.colorizer")
require("config.todo")
require("config.hlslens")
require("config.hop")
--[[ require("config.navigator") ]]
require("config.mason")
require("config.lspsaga")
require("config.null-ls")
require("config.fold")
require("config.dial")
require("config.neoscroll")
require("config.auto-save")
require("config.link")
require("config.go")
require("config.sad")
require("config.glance")

require("options")
