require("indent_blankline").setup({
  buftype_exclude = { "terminal" },
  filetype_exclude = {
    "dashboard",
    "packer",
    "mason-lspconfig",
    "mason",
    "lspsaga",
    "noice",
    "lir",
    "help",
    "harpoon",
  },
  show_current_context = true,
  show_current_context_start = false,
  context_patterns = {
    "class",
    "return",
    "function",
    "method",
    "^if",
    "^while",
    "jsx_element",
    "^for",
    "^object",
    "^table",
    "block",
    "arguments",
    "if_statement",
    "else_clause",
    "jsx_element",
    "jsx_self_closing_element",
    "try_statement",
    "catch_clause",
    "import_statement",
    "operation_type",
  },
})

vim.cmd("let g:indent_blankline_char = '|'")
