require("config.tokyonight")
require("config.dashboard")
-- require("config.whichkey")
require("config.lir")
require("config.telescope")
require("config.lualine")
require("config.bufferline")
require("config.noice")
require("config.treesitter")
require("config.specs")
require("config.hlargs")
require("config.neogen")
require("config.mason")
require("config.lsp")
require("config.todo")
require("config.incline")
require("config.diffview")
require("config.lspsaga")
require("config.windows")
require("config.dial")
require("config.null-ls")
--[[ require("config.nvim-tree") ]]
require("config.colorizer")
require("config.colorizer")
require("config.blankline")
require("config.autopairs")
require("config.toggleterm")
require("config.comment")
require("config.neoscroll")
require("config.scrollbar")
require("config.hlslens")
require("config.fidget")

