local M = {}

M.enable = {
  lualine = true,
  theme = true,
  flash = true,
  typescript_tools = true,
  noice = true,
  yanky = true,
  muren = true,
  which_key = true,
  nvim_tree = true,
  scroll = true,
  go = true,
  cmp = true,
  fold = true,
  ts = {
    treesitter = true,
    autotag = true,
    context = true,
    illuminate = true,
  },
  quickfix = {
    diaglist = true,
    bqf = true,
  },
  rust = {
    rust_tools = true,
    rust_vim = true,
    crates = true,
  },
  text_objects = {
    treesitter = true,
    various = true,
    comment = true,
    targets = true,
  },
  mini = {
    indentscope = false,
    move = true,
    pairs = false,
    splitjoin = true,
  },
  comments = {
    todo_comments = true,
    comment = true,
  },
  git = {
    git_signs = true,
    git_blame = false,
  },
  lsp = {
    mason = true,
    mason_lspconfig = true,
    lspconfig = true,
    lspsaga = false,
    format_on_save = true,
  },
  utils = {
    dial = true,
    dressing = true,
    plenary = true,
    dev_icons = true,
    harpoon = true,
    popup = true,
    virt_column = true,
    buffalo = true,
    sentiment = true,
    surround = true,
    vim_repeat = true,
    highlight_colors = true,
    tabout = true,
    word_motion = true,
    neodev = true,
    floaterm = true,
    suda = true,
    codeium = true,
    notify = true,
    hl_chunk = true,
  },
}

return M
