return {
  {
    -- "huggingface/hfcc.nvim",
    -- event = "BufReadPre",
    -- opts = {
    --   -- api_token = "HUGGING_FACE_HUB_TOKEN",
    --   model = "bigcode/starcoder",
    --   query_params = {
    --     max_new_tokens = 200,
    --   },
    -- },
    -- init = function()
    --   vim.api.nvim_create_user_command("StarCoder", function()
    --     require("hfcc.completion").complete()
    --   end, {})
    -- end,
  },
  {
    "Exafunction/codeium.vim",
    event = "VeryLazy",
    config = function()
      -- vim.g.codeium_disable_bindings = 1
    end,
  },
  -- {
  --   "jackMort/ChatGPT.nvim",
  --   event = "BufReadPre",
  --   dependencies = {
  --     "MunifTanjim/nui.nvim",
  --     "nvim-lua/plenary.nvim",
  --     "nvim-telescope/telescope.nvim"
  --   },
  --   config = function()
  --     local config = {
  --       api_key_cmd = nil,
  --       yank_register = "+",
  --       edit_with_instructions = {
  --         diff = false,
  --         keymaps = {
  --           close = "<C-c>",
  --           accept = "<C-y>",
  --           toggle_diff = "<C-d>",
  --           toggle_settings = "<C-o>",
  --           cycle_windows = "<Tab>",
  --           use_output_as_input = "<C-i>",
  --         },
  --       },
  --       chat = {
  --         welcome_message = "WELCOME MESSAGE",
  --         loading_text = "Loading, please wait ...",
  --         question_sign = "",
  --         answer_sign = "ﮧ",
  --         max_line_length = 120,
  --         sessions_window = {
  --           border = {
  --             -- style = "rounded",
  --             text = {
  --               top = " Sessions ",
  --             },
  --           },
  --           win_options = {
  --             winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --           },
  --         },
  --         keymaps = {
  --           close = { "<C-c>" },
  --           yank_last = "<C-y>",
  --           yank_last_code = "<C-k>",
  --           scroll_up = "<C-u>",
  --           scroll_down = "<C-d>",
  --           new_session = "<C-n>",
  --           cycle_windows = "<Tab>",
  --           cycle_modes = "<C-f>",
  --           select_session = "<Space>",
  --           rename_session = "r",
  --           delete_session = "d",
  --           draft_message = "<C-d>",
  --           toggle_settings = "<C-o>",
  --           toggle_message_role = "<C-r>",
  --           toggle_system_role_open = "<C-s>",
  --         },
  --       },
  --       popup_layout = {
  --         default = "center",
  --         center = {
  --           width = "80%",
  --           height = "80%",
  --         },
  --         right = {
  --           width = "30%",
  --           width_settings_open = "50%",
  --         },
  --       },
  --       popup_window = {
  --         border = {
  --           highlight = "FloatBorder",
  --           -- style = "rounded",
  --           text = {
  --             top = " ChatGPT ",
  --           },
  --         },
  --         win_options = {
  --           wrap = true,
  --           linebreak = true,
  --           foldcolumn = "1",
  --           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --         },
  --         buf_options = {
  --           filetype = "markdown",
  --         },
  --       },
  --       system_window = {
  --         border = {
  --           highlight = "FloatBorder",
  --           -- style = "rounded",
  --           text = {
  --             top = " SYSTEM ",
  --           },
  --         },
  --         win_options = {
  --           wrap = true,
  --           linebreak = true,
  --           foldcolumn = "2",
  --           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --         },
  --       },
  --       popup_input = {
  --         prompt = "  ",
  --         border = {
  --           highlight = "FloatBorder",
  --           -- style = "rounded",
  --           text = {
  --             top_align = "center",
  --             top = " Prompt ",
  --           },
  --         },
  --         win_options = {
  --           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --         },
  --         submit = "<C-Enter>",
  --         submit_n = "<Enter>",
  --       },
  --       settings_window = {
  --         border = {
  --           -- style = "rounded",
  --           text = {
  --             top = " Settings ",
  --           },
  --         },
  --         win_options = {
  --           winhighlight = "Normal:Normal,FloatBorder:FloatBorder",
  --         },
  --       },
  --       openai_params = {
  --         model = "gpt-3.5-turbo",
  --         frequency_penalty = 0,
  --         presence_penalty = 0,
  --         max_tokens = 300,
  --         temperature = 0,
  --         top_p = 1,
  --         n = 1,
  --       },
  --       openai_edit_params = {
  --         model = "code-davinci-edit-001",
  --         temperature = 0,
  --         top_p = 1,
  --         n = 1,
  --       },
  --       actions_paths = {},
  --       show_quickfixes_cmd = "Trouble quickfix",
  --       predefined_chat_gpt_prompts = "https://raw.githubusercontent.com/f/awesome-chatgpt-prompts/main/prompts.csv",
  --     }
  --
  --     require("chatgpt").setup({ config })
  --   end,
  -- },
}
